### ISSUE TITLE
Bump and release version with RT44 fix

### ISSUE THREAD

**Issue by erdgeist** [bulletproofnetworks/roust#28]
Hey,

for a conference end of year we need to interact with a newer RT. Can you please roll a new gem with the last fix so I can more easily require roust, without dependencies into git on the production system?

**Comment by nerdyness** [comment]
Apologies mate, I forgot to push a new gem! I'll do it tomorrow :+1:

Cheers,
@nerdyness

**Comment by nerdyness** [comment]
https://rubygems.org/gems/roust

1.8.9 has been pushed up. Let me know if you see any issues, @erdgeist
